# Generated by Django 6.0.6 on 2026-06-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('cng', 'CNG'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_share_percent_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-vehicle override of owner share %. Takes priority over owner/global default.', max_digits=5, null=True)),
                ('current_odometer', models.PositiveIntegerField(default=0, help_text='Latest known odometer reading (km).')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented Out'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('permit_expiry', models.DateField(blank=True, null=True)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
                ('rc_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='owners.carowner')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='vehicles.vehicle')),
            ],
        ),
    ]
