# Generated by Django 6.0.6 on 2026-07-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_share_percent_override',
        ),
        migrations.CreateModel(
            name='VehicleOwnerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_daily_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_extra_km_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('owner_damage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rate', to='vehicles.vehicle')),
            ],
        ),
    ]
