# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Car Rental Co.', max_length=150)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('company_upi_id', models.CharField(blank=True, default='', help_text="The company's own UPI ID, used to generate the dynamic customer-payment QR.", max_length=100)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_footer_note', models.TextField(blank=True, default='Thank you for choosing us. Drive safe!')),
                ('invoice_terms', models.TextField(blank=True, default='1. Customer is responsible for the vehicle during the rental period.\n2. Fuel is to be returned at the same level as at pickup.\n3. Any damages will be charged as per assessment.\n4. Late return will be charged as per the late fee policy.')),
                ('default_owner_share_percent', models.DecimalField(decimal_places=2, default=70.0, help_text='Default % of rental revenue that goes to the car owner. Can be overridden per-vehicle.', max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='GST % applied on top of the base rental amount across the app.', max_digits=5)),
                ('late_fee_per_hour', models.DecimalField(decimal_places=2, default=100.0, help_text='Penalty charged per hour when the vehicle is returned after the booked end time.', max_digits=10)),
                ('extra_km_charge_per_km', models.DecimalField(decimal_places=2, default=10.0, help_text='Charge per km when the distance covered exceeds the included free km limit.', max_digits=10)),
                ('free_km_per_day', models.PositiveIntegerField(default=200, help_text='Free km included per booked day before extra km charges apply.')),
                ('grace_period_minutes', models.PositiveIntegerField(default=30, help_text='Grace period (in minutes) after the booked end time before late fee starts applying.')),
                ('standard_shift_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard working hours per day used to pro-rate daily salary from monthly salary.', max_digits=4)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('session_timeout_hours', models.PositiveIntegerField(default=24, help_text='Admin must re-login after this many hours of inactivity from last login.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
