# Generated by Django 6.0.6 on 2026-07-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsettings',
            name='default_owner_share_percent',
        ),
        migrations.RemoveField(
            model_name='applicationsettings',
            name='late_fee_per_hour',
        ),
    ]
