# Generated by Django 6.0.6 on 2026-07-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_applicationsettings_booking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsettings',
            name='booking_lock_hours',
        ),
    ]
