# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('id_proof_type', models.CharField(choices=[('driving_license', 'Driving License'), ('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('other', 'Other')], default='driving_license', max_length=30)),
                ('id_proof_number', models.CharField(blank=True, default='', max_length=50)),
                ('id_proof_photo_front', models.ImageField(blank=True, null=True, upload_to='customers/id_proofs/')),
                ('id_proof_photo_back', models.ImageField(blank=True, null=True, upload_to='customers/id_proofs/')),
                ('driving_license_number', models.CharField(blank=True, default='', max_length=50)),
                ('driving_license_photo', models.ImageField(blank=True, null=True, upload_to='customers/licenses/')),
                ('customer_photo', models.ImageField(blank=True, help_text='Photo of the customer taken at pickup, for record/verification.', null=True, upload_to='customers/photos/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
