# Generated by Django 6.0.6 on 2026-06-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('owners', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_vehicles', models.PositiveIntegerField(default=1, help_text='Number of vehicles requested under this booking (usually 1).')),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('purpose', models.CharField(blank=True, default='', help_text='Purpose/reason for the trip.', max_length=200)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('booked_days', models.PositiveIntegerField(default=1)),
                ('odometer_start', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('payment_timing', models.CharField(choices=[('now', 'Pay Now'), ('later', 'Pay Later')], default='later', max_length=10)),
                ('security_deposit_collected', models.BooleanField(default=False)),
                ('security_deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('owner_share_percent_snapshot', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('late_fee_per_hour_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_km_charge_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_km_total_snapshot', models.PositiveIntegerField(default=0, help_text='Free km allowed for the full booking.')),
                ('grace_period_minutes_snapshot', models.PositiveIntegerField(default=30)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_km_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_notes', models.TextField(blank=True, default='')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('status', models.CharField(choices=[('booked', 'Booked (Upcoming)'), ('active', 'Active (Car Out)'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='booked', max_length=12)),
                ('closing_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('single', 'Single Rental'), ('collective', 'Collective / Bulk')], default='single', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='owners.carowner')),
                ('rentals', models.ManyToManyField(blank=True, related_name='owner_payouts', to='rentals.rental')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
