# Generated by Django 6.0.6 on 2026-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_created_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='owner_daily_amount_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='owner_damage_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rental',
            name='owner_extra_km_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
