# Generated by Django 6.0.6 on 2026-07-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_owner_rate_and_rental_snapshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='late_fee_per_hour_snapshot',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='owner_share_percent_snapshot',
        ),
    ]
