# Generated by Django 6.0.6 on 2026-07-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_rental_late_fee_per_hour_snapshot_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rentals', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='rental',
            name='driver_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_venue',
            field=models.CharField(choices=[('parking', 'Parking'), ('airport', 'Airport'), ('other', 'Other Location')], default='parking', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_venue_other_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_venue_other_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
