# Generated by Django 6.0.6 on 2026-07-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rental_vehicle_booking_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rental',
            new_name='rentals_ren_status_6cea10_idx',
            old_name='rentals_ren_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='rental',
            new_name='rentals_ren_payment_5fe13c_idx',
            old_name='rentals_ren_pmt_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='rental',
            new_name='rentals_ren_schedul_bdd203_idx',
            old_name='rentals_ren_sched_start_idx',
        ),
        migrations.RenameIndex(
            model_name='rental',
            new_name='rentals_ren_schedul_259a56_idx',
            old_name='rentals_ren_sched_end_idx',
        ),
    ]
