# Generated by Django 6.0.6 on 2026-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rename_rentals_ren_status_created_idx_rentals_ren_status_6cea10_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpayout',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
