# Generated by Django 6.0.6 on 2026-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_ownerpayout_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='fees_waived',
            field=models.BooleanField(default=False, help_text='If set, late fee and extra km charges are calculated and recorded but not billed to the customer (e.g. vehicle technical issue caused the delay/extra distance).'),
        ),
        migrations.AddField(
            model_name='rental',
            name='waiver_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
