# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Vehicle Maintenance'), ('office', 'Office / Rent'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('misc_income', 'Other Income'), ('misc_expense', 'Other Expense')], default='misc_expense', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Finance Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
