# Generated by Django 6.0.6 on 2026-07-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='category',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Vehicle Maintenance'), ('office', 'Office / Rent'), ('marketing', 'Marketing'), ('insurance', 'Insurance'), ('rental_cancellation', 'Rental Cancellation'), ('misc_income', 'Other Income'), ('misc_expense', 'Other Expense')], default='misc_expense', max_length=20),
        ),
    ]
