# Generated by Django 6.0.6 on 2026-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financeentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
