# Generated by Django 6.0.6 on 2026-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('upi_payee_name', models.CharField(blank=True, default='', help_text='Name to display/encode on the UPI QR. Defaults to owner name if blank.', max_length=150)),
                ('default_share_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override of the global owner-share %. Leave blank to use global default.', max_digits=5, null=True)),
                ('id_proof_number', models.CharField(blank=True, default='', max_length=50)),
                ('id_proof_photo', models.ImageField(blank=True, null=True, upload_to='owners/id_proofs/')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
