# Generated by Django 6.0.6 on 2026-07-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='default_share_percent',
        ),
    ]
