# Generated by Django 6.0.6 on 2026-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmember_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('cl', 'Casual Leave'), ('auth_leave', 'Authorized Leave')], max_length=10),
        ),
    ]
