# Generated by Django 6.0.6 on 2026-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_shifts_and_attendance_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='work_fri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_mon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_thu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_tue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_wed',
            field=models.BooleanField(default=True),
        ),
    ]
