# Generated by Django 6.0.6 on 2026-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('cleaner', 'Cleaner'), ('watchman', 'Watchman'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('front_desk', 'Front Desk'), ('employee', 'Employee'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
