# Generated by Django 6.0.6 on 2026-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staffmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
